# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api_models.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api_models.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x61pi_models.proto\",\n\x05Point\x12\x10\n\x08Latitude\x18\x01 \x01(\x01\x12\x11\n\tLongitude\x18\x02 \x01(\x01\"W\n\x0bSignalPoint\x12\x10\n\x08Latitude\x18\x01 \x01(\x01\x12\x11\n\tLongitude\x18\x02 \x01(\x01\x12\x13\n\x0bReliability\x18\x03 \x01(\x01\x12\x0e\n\x06Signal\x18\x04 \x01(\x01\"\x91\x01\n\x11\x41\x64\x64MeasureRequest\x12\x10\n\x08Latitude\x18\x01 \x01(\x01\x12\x11\n\tLongitude\x18\x02 \x01(\x01\x12\x0e\n\x06Signal\x18\x03 \x01(\x01\x12\x14\n\x0cOperatorName\x18\x04 \x01(\t\x12\x0e\n\x06UserId\x18\x05 \x01(\x03\x12\x0c\n\x04Time\x18\x06 \x01(\x03\x12\x13\n\x0bNetworkName\x18\x07 \x01(\t\"[\n\x10SignalMapRequest\x12\x1c\n\x0c\x42orderPoints\x18\x01 \x03(\x0b\x32\x06.Point\x12\x14\n\x0cOperatorName\x18\x02 \x01(\t\x12\x13\n\x0bNetworkName\x18\x03 \x01(\t\"1\n\x11SignalMapResponse\x12\x1c\n\x06Points\x18\x01 \x03(\x0b\x32\x0c.SignalPoint\"\x1f\n\x0cScoreRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"\x1e\n\rScoreResponse\x12\r\n\x05Score\x18\x02 \x01(\x01\x62\x06proto3')
)




_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Latitude', full_name='Point.Latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Longitude', full_name='Point.Longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=64,
)


_SIGNALPOINT = _descriptor.Descriptor(
  name='SignalPoint',
  full_name='SignalPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Latitude', full_name='SignalPoint.Latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Longitude', full_name='SignalPoint.Longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Reliability', full_name='SignalPoint.Reliability', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Signal', full_name='SignalPoint.Signal', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=153,
)


_ADDMEASUREREQUEST = _descriptor.Descriptor(
  name='AddMeasureRequest',
  full_name='AddMeasureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Latitude', full_name='AddMeasureRequest.Latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Longitude', full_name='AddMeasureRequest.Longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Signal', full_name='AddMeasureRequest.Signal', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OperatorName', full_name='AddMeasureRequest.OperatorName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UserId', full_name='AddMeasureRequest.UserId', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Time', full_name='AddMeasureRequest.Time', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NetworkName', full_name='AddMeasureRequest.NetworkName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=301,
)


_SIGNALMAPREQUEST = _descriptor.Descriptor(
  name='SignalMapRequest',
  full_name='SignalMapRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='BorderPoints', full_name='SignalMapRequest.BorderPoints', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OperatorName', full_name='SignalMapRequest.OperatorName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NetworkName', full_name='SignalMapRequest.NetworkName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=394,
)


_SIGNALMAPRESPONSE = _descriptor.Descriptor(
  name='SignalMapResponse',
  full_name='SignalMapResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Points', full_name='SignalMapResponse.Points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=445,
)


_SCOREREQUEST = _descriptor.Descriptor(
  name='ScoreRequest',
  full_name='ScoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='ScoreRequest.user_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=447,
  serialized_end=478,
)


_SCORERESPONSE = _descriptor.Descriptor(
  name='ScoreResponse',
  full_name='ScoreResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Score', full_name='ScoreResponse.Score', index=0,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=510,
)

_SIGNALMAPREQUEST.fields_by_name['BorderPoints'].message_type = _POINT
_SIGNALMAPRESPONSE.fields_by_name['Points'].message_type = _SIGNALPOINT
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['SignalPoint'] = _SIGNALPOINT
DESCRIPTOR.message_types_by_name['AddMeasureRequest'] = _ADDMEASUREREQUEST
DESCRIPTOR.message_types_by_name['SignalMapRequest'] = _SIGNALMAPREQUEST
DESCRIPTOR.message_types_by_name['SignalMapResponse'] = _SIGNALMAPRESPONSE
DESCRIPTOR.message_types_by_name['ScoreRequest'] = _SCOREREQUEST
DESCRIPTOR.message_types_by_name['ScoreResponse'] = _SCORERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'api_models_pb2'
  # @@protoc_insertion_point(class_scope:Point)
  })
_sym_db.RegisterMessage(Point)

SignalPoint = _reflection.GeneratedProtocolMessageType('SignalPoint', (_message.Message,), {
  'DESCRIPTOR' : _SIGNALPOINT,
  '__module__' : 'api_models_pb2'
  # @@protoc_insertion_point(class_scope:SignalPoint)
  })
_sym_db.RegisterMessage(SignalPoint)

AddMeasureRequest = _reflection.GeneratedProtocolMessageType('AddMeasureRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDMEASUREREQUEST,
  '__module__' : 'api_models_pb2'
  # @@protoc_insertion_point(class_scope:AddMeasureRequest)
  })
_sym_db.RegisterMessage(AddMeasureRequest)

SignalMapRequest = _reflection.GeneratedProtocolMessageType('SignalMapRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNALMAPREQUEST,
  '__module__' : 'api_models_pb2'
  # @@protoc_insertion_point(class_scope:SignalMapRequest)
  })
_sym_db.RegisterMessage(SignalMapRequest)

SignalMapResponse = _reflection.GeneratedProtocolMessageType('SignalMapResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNALMAPRESPONSE,
  '__module__' : 'api_models_pb2'
  # @@protoc_insertion_point(class_scope:SignalMapResponse)
  })
_sym_db.RegisterMessage(SignalMapResponse)

ScoreRequest = _reflection.GeneratedProtocolMessageType('ScoreRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCOREREQUEST,
  '__module__' : 'api_models_pb2'
  # @@protoc_insertion_point(class_scope:ScoreRequest)
  })
_sym_db.RegisterMessage(ScoreRequest)

ScoreResponse = _reflection.GeneratedProtocolMessageType('ScoreResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCORERESPONSE,
  '__module__' : 'api_models_pb2'
  # @@protoc_insertion_point(class_scope:ScoreResponse)
  })
_sym_db.RegisterMessage(ScoreResponse)


# @@protoc_insertion_point(module_scope)
